// Generate the plugin catalog (plugins.json), the root README catalog table, and each plugin README's
// "Details" block — all from manifest.json + CHANGELOG.md (the single sources of truth). Run with
// `--check` to fail (exit 1) when committed files are stale or a manifest/changelog version drifts.
//
// Usage: node scripts/catalog.mjs [--check]
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const SKIP = new Set(['node_modules', 'scripts', 'docs', '.git', '.github', '.superpowers', 'dist', '.remember']);

const DETAILS_RE = /<!-- BEGIN DETAILS[\s\S]*?<!-- END DETAILS -->/;
const CATALOG_RE = /<!-- BEGIN PLUGIN CATALOG -->[\s\S]*?<!-- END PLUGIN CATALOG -->/;

function discoverPlugins() {
  return readdirSync(ROOT)
    .filter((name) => !SKIP.has(name) && !name.startsWith('.'))
    .filter((name) => statSync(join(ROOT, name)).isDirectory())
    .filter((name) => existsSync(join(ROOT, name, 'manifest.json')))
    .sort();
}

// Top released CHANGELOG heading: `## [x.y.z] — YYYY-MM-DD` (skips `## [Unreleased]`).
function readChangelogTop(id) {
  const path = join(ROOT, id, 'CHANGELOG.md');
  if (!existsSync(path)) throw new Error(`${id}: missing CHANGELOG.md`);
  const m = readFileSync(path, 'utf8').match(/^##\s*\[(\d+\.\d+\.\d+)\]\s*[—–-]\s*(\d{4}-\d{2}-\d{2})/m);
  if (!m) throw new Error(`${id}: CHANGELOG.md has no released "## [x.y.z] — YYYY-MM-DD" heading`);
  return { version: m[1], date: m[2] };
}

function buildEntry(id) {
  const manifest = JSON.parse(readFileSync(join(ROOT, id, 'manifest.json'), 'utf8'));
  const changelog = readChangelogTop(id);
  if (manifest.version !== changelog.version) {
    throw new Error(
      `${id}: version drift — manifest.json is ${manifest.version} but the top CHANGELOG entry is ${changelog.version}`,
    );
  }
  return {
    id: manifest.id,
    name: manifest.name,
    version: manifest.version,
    type: manifest.type,
    status: manifest.status ?? 'development',
    description: manifest.description ?? '',
    author: manifest.author ?? '',
    license: manifest.license ?? '',
    keywords: manifest.keywords ?? [],
    minOpenWAVersion: manifest.minOpenWAVersion ?? null,
    testedOpenWAVersion: manifest.testedOpenWAVersion ?? null,
    releasedAt: changelog.date,
    repoPath: manifest.id,
    repoUrl: manifest.repository ?? null,
    homepage: manifest.homepage ?? null,
    download: manifest.repository
      ? `${manifest.repository}/releases/download/${manifest.id}-v${manifest.version}/${manifest.id}.zip`
      : null,
  };
}

const authorName = (author) => author.replace(/\s*<[^>]*>\s*/, '').trim();

function detailsBlock(e) {
  return [
    '<!-- BEGIN DETAILS (generated by scripts/catalog.mjs — do not edit by hand) -->',
    '| Field | Value |',
    '| ----- | ----- |',
    `| **Identifier** | \`${e.id}\` |`,
    `| **Version** | ${e.version} |`,
    `| **Released** | ${e.releasedAt} |`,
    `| **Status** | ${e.status} |`,
    `| **Author** | ${authorName(e.author)} |`,
    `| **License** | ${e.license} |`,
    `| **Type** | \`${e.type}\` |`,
    `| **Requires OpenWA** | ≥ ${e.minOpenWAVersion} (tested ${e.testedOpenWAVersion}) |`,
    `| **Keywords** | ${e.keywords.join(', ')} |`,
    `| **Repository** | [OpenWA-plugins/${e.id}](${e.homepage}) |`,
    '<!-- END DETAILS -->',
  ].join('\n');
}

function catalogTable(entries) {
  const rows = entries.map((e) => `| [\`${e.id}\`](./${e.repoPath}) | ${e.description} | ${e.version} | ${e.status} |`);
  return [
    '<!-- BEGIN PLUGIN CATALOG -->',
    '| Plugin | Description | Version | Status |',
    '| ------ | ----------- | ------- | ------ |',
    ...rows,
    '<!-- END PLUGIN CATALOG -->',
  ].join('\n');
}

// Returns the would-be content for a file with one marker region replaced; throws if the marker is absent.
function replaceRegion(path, regex, replacement, label) {
  const current = readFileSync(path, 'utf8');
  if (!regex.test(current)) throw new Error(`${path}: missing ${label} markers`);
  return current.replace(regex, replacement);
}

const entries = discoverPlugins().map(buildEntry);

const targets = [
  { path: join(ROOT, 'plugins.json'), next: JSON.stringify(entries, null, 2) + '\n' },
  { path: join(ROOT, 'README.md'), next: replaceRegion(join(ROOT, 'README.md'), CATALOG_RE, catalogTable(entries), 'PLUGIN CATALOG') },
  ...entries.map((e) => {
    const path = join(ROOT, e.id, 'README.md');
    return { path, next: replaceRegion(path, DETAILS_RE, detailsBlock(e), 'DETAILS') };
  }),
];

const stale = targets.filter((t) => !existsSync(t.path) || readFileSync(t.path, 'utf8') !== t.next);

if (CHECK) {
  if (stale.length) {
    console.error('Catalog is out of date. Run `npm run catalog` and commit:');
    for (const t of stale) console.error(`  - ${t.path.replace(ROOT + '/', '')}`);
    process.exit(1);
  }
  console.log(`Catalog up to date (${entries.length} plugin(s)).`);
} else {
  for (const t of stale) writeFileSync(t.path, t.next);
  console.log(`Catalog written (${entries.length} plugin(s)); updated ${stale.length} file(s).`);
}
