// Catalog passthrough test: verifies that plugins.json carries i18n blocks for any plugin whose
// manifest.json has an `i18n` field. plugins.json is generated by `npm run catalog`; the
// version/changelog drift gate lives in scripts/catalog.mjs itself.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('plugins.json carries i18n for a plugin whose manifest has it', () => {
  const catalog = JSON.parse(readFileSync(new URL('../plugins.json', import.meta.url), 'utf8'));
  const entries = catalog.plugins ?? catalog;
  const withI18n = entries.filter(e => e.i18n);
  assert.ok(withI18n.length > 0, 'expected at least one plugin entry with i18n');
  for (const e of withI18n) assert.ok(e.i18n.es && e.i18n['zh-CN'], `${e.id} i18n should include es + zh-CN`);
});

test('every stable plugin ships a full i18n block', () => {
  const catalog = JSON.parse(readFileSync(new URL('../plugins.json', import.meta.url), 'utf8'));
  const entries = catalog.plugins ?? catalog;
  const LOCALES = ['es', 'fr', 'it', 'ar', 'he', 'te', 'zh-CN', 'zh-HK'];
  for (const e of entries.filter(e => e.status === 'stable')) {
    assert.ok(e.i18n, `${e.id} (stable) has no i18n block`);
    for (const l of LOCALES) assert.ok(e.i18n[l], `${e.id} i18n missing locale ${l}`);
  }
});
