// Catalog passthrough test: verifies that plugins.json carries i18n blocks for any plugin whose
// manifest.json has an `i18n` field. plugins.json is generated by `npm run catalog`; the
// version/changelog drift gate lives in scripts/catalog.mjs itself.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync } from 'node:fs';

// Three of the checks below iterate a list that can come back empty — no plugin directories, no stable
// entries, no catalog entries at all — and an empty loop is indistinguishable from a passing one. Proven
// rather than assumed: run this file against a tree holding `{"plugins":[]}` and no plugin directories,
// and three of the five tests stay green having examined nothing. Only the two that already assert a
// non-empty list go red.
//
// Asserting the inputs once here is better than counting units inside each check: while this passes,
// none of those empty-iteration paths can fire, and when an input disappears THIS test names which one.
// Discovery is the widest version of the problem — `root` is derived from this file's own location, so
// moving the file empties every list below at once.
test('the catalog supplies what the checks below need', () => {
  const root = new URL('../', import.meta.url);
  const dirs = readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(new URL(`${d.name}/manifest.json`, root)))
    .map((d) => d.name);
  const catalog = JSON.parse(readFileSync(new URL('plugins.json', root), 'utf8'));
  const entries = catalog.plugins ?? catalog;

  assert.ok(dirs.length > 0, `no plugin directories discovered under ${root.pathname}`);
  assert.ok(entries.length > 0, 'plugins.json lists no entries — the drift checks would compare nothing');
  assert.ok(
    entries.some((e) => e.status === 'stable'),
    'no entry is stable — the full-i18n check would iterate an empty list',
  );
  // The config-translation check skips a plugin with no config fields or no i18n. That skip is correct
  // per plugin and fatal across all of them, so assert at least one plugin actually reaches the loop —
  // and reaches its INNER loop too: that one iterates the locales, so a manifest carrying `"i18n": {}`
  // satisfies a truthy check while the check itself still examines zero locales.
  assert.ok(
    dirs.some((d) => {
      const m = JSON.parse(readFileSync(new URL(`${d}/manifest.json`, root), 'utf8'));
      return Object.keys(m.configSchema?.properties ?? {}).length > 0 && Object.keys(m.i18n ?? {}).length > 0;
    }),
    'no plugin has both configSchema fields and a non-empty i18n block — the config-translation check would examine nothing',
  );
});

test('plugins.json carries i18n for a plugin whose manifest has it', () => {
  const catalog = JSON.parse(readFileSync(new URL('../plugins.json', import.meta.url), 'utf8'));
  const entries = catalog.plugins ?? catalog;
  const withI18n = entries.filter(e => e.i18n);
  assert.ok(withI18n.length > 0, 'expected at least one plugin entry with i18n');
  for (const e of withI18n) assert.ok(e.i18n.es && e.i18n['zh-CN'], `${e.id} i18n should include es + zh-CN`);
});

test('every stable plugin ships a full i18n block', () => {
  const catalog = JSON.parse(readFileSync(new URL('../plugins.json', import.meta.url), 'utf8'));
  const entries = catalog.plugins ?? catalog;
  const LOCALES = ['es', 'fr', 'it', 'ar', 'he', 'te', 'zh-CN', 'zh-HK'];
  for (const e of entries.filter(e => e.status === 'stable')) {
    assert.ok(e.i18n, `${e.id} (stable) has no i18n block`);
    for (const l of LOCALES) assert.ok(e.i18n[l], `${e.id} i18n missing locale ${l}`);
  }
});

// A locale that carries `name`/`description` but no `config` block passes every check there was:
// catalog.mjs only warns when a locale is entirely ABSENT, and warns rather than fails. The result is
// a plugin whose name and description translate while all of its config-field titles stay English —
// voice-transcription's `es` did exactly that, and being `beta` also put it outside the stable-only
// test above.
test('a locale that translates a plugin translates all of its config fields', () => {
  const root = new URL('../', import.meta.url);
  const dirs = readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(new URL(`${d.name}/manifest.json`, root)))
    .map((d) => d.name);

  const gaps = [];
  for (const dir of dirs) {
    const m = JSON.parse(readFileSync(new URL(`${dir}/manifest.json`, root), 'utf8'));
    const fields = Object.keys(m.configSchema?.properties ?? {});
    if (!fields.length || !m.i18n) continue;
    // Only locales that bother to translate at all are held to this — a plugin may legitimately ship
    // fewer locales than another.
    for (const [locale, block] of Object.entries(m.i18n)) {
      const translated = Object.keys(block.config ?? {});
      const missing = fields.filter((f) => !translated.includes(f));
      if (missing.length) gaps.push(`${dir} [${locale}]: ${missing.length}/${fields.length} untranslated`);
    }
  }
  assert.deepEqual(gaps, []);
});

// The catalog is the data source the in-dashboard marketplace reads, and it carried nothing about what
// a plugin binds — so "install only plugins you trust" had no in-product evidence to work from. These
// hold the published fields to the manifests they come from.
test('the catalog publishes what each plugin declares', () => {
  const root = new URL('../', import.meta.url);
  const catalog = JSON.parse(readFileSync(new URL('plugins.json', root), 'utf8'));
  const entries = catalog.plugins ?? catalog;

  const drift = [];
  for (const e of entries) {
    const m = JSON.parse(readFileSync(new URL(`${e.id}/manifest.json`, root), 'utf8'));
    const declared = m.permissions ?? [];
    if (JSON.stringify(e.permissions ?? []) !== JSON.stringify(declared)) {
      drift.push(`${e.id}: permissions ${JSON.stringify(e.permissions)} != manifest ${JSON.stringify(declared)}`);
    }
    if (JSON.stringify(e.net ?? null) !== JSON.stringify(m.net ?? null)) {
      drift.push(`${e.id}: net differs from manifest`);
    }
    const routes = Array.isArray(m.ingress) ? m.ingress.map((r) => r.route) : null;
    const published = Array.isArray(e.ingress) ? e.ingress.map((r) => r.route) : null;
    if (JSON.stringify(published) !== JSON.stringify(routes)) {
      drift.push(`${e.id}: ingress routes ${JSON.stringify(published)} != manifest ${JSON.stringify(routes)}`);
    }
  }
  assert.deepEqual(drift, []);
});

test('the ingress-declaring plugins publish their route shapes', () => {
  // Two plugins declare ingress. A provisioned ingress route is a @Public() endpoint, so which routes
  // exist and whether they are signed is the part worth seeing before an install.
  const catalog = JSON.parse(readFileSync(new URL('../plugins.json', import.meta.url), 'utf8'));
  const withIngress = (catalog.plugins ?? catalog).filter((e) => Array.isArray(e.ingress) && e.ingress.length);

  assert.ok(withIngress.length >= 1, 'expected at least one plugin publishing ingress routes');
  for (const e of withIngress) {
    for (const r of e.ingress) {
      assert.ok(typeof r.route === 'string' && r.route.length, `${e.id} ingress entry has no route`);
      assert.ok('signature' in r, `${e.id} ingress entry does not say whether it is signed`);
      // Pinned so a published field always has a manifest field behind it: an earlier `methods` column
      // read straight through to a key `PluginIngressRoute` does not define, so it was null every time.
      assert.deepEqual(Object.keys(r).sort(), ['route', 'signature'], `${e.id} ingress entry shape`);
    }
  }
});
